DROP TABLE IF EXISTS T_BLOG;
DROP TABLE IF EXISTS T_ARTICLE;
DROP TABLE IF EXISTS T_AUTHOR;

CREATE TABLE T_BLOG (
  ID           BIGINT IDENTITY,
  TITLE        VARCHAR(255) NOT NULL,
  AUTHOR       VARCHAR(20),
  CATEGORY     VARCHAR(50),
  URL          VARCHAR(512),
  OTHER        VARCHAR(1024),
  CREATER      VARCHAR(20),
  PUBLISH_DATE DATE,
  PRIMARY KEY (id)
);

CREATE TABLE T_AUTHOR (
  ID          BIGINT IDENTITY,
  USER_ID     VARCHAR(32) NOT NULL UNIQUE,
  USER_NAME   VARCHAR(32),
  EMAIL       VARCHAR(100),
  DESCRIBE_INFO    VARCHAR(512),
  PRIMARY KEY (ID)
);

CREATE TABLE T_ARTICLE (
  ID BIGINT IDENTITY PRIMARY KEY,
  TITLE varchar(50) not null,
  CATEGORY varchar(50),
  URL varchar(256),
  PUBLISH_DATE date,
  AUTHOR_ID BIGINT NOT NULL,
  FOREIGN KEY (AUTHOR_ID) REFERENCES T_AUTHOR (ID)
);



